version: '3.8'

services:
  schnapsen-duo-server:
    build:
      context: ./schnapsen-duo-server
      args:
        - AMQP_URL=${AMQP_URL}
    container_name: schnapsen-duo-server
    command: schnapsen-duo-server
    ports:
      - "6060:6060"
    restart: on-failure
    networks:
      - game-night-network
    environment:
      - HOST_ADDR=0.0.0.0:6060
      - PUBLIC_ADDR=${SCHNAPSEN_DUO_PUBLIC_ADDR}
      - PRIVATE_ADDR=${SCHNAPSEN_DUO_PRIVATE_ADDR}
      - REGION=${REGION}
      - DEBUG=${DEBUG}
  
  schnapsen-ai-client:
    build:
      context: ./schnapsen-ai-client
    container_name: schnapsen-ai-client
    command: bun run index.ts
    restart: on-failure
    networks:
      - game-night-network
    environment:
      - AMQP_URL=${AMQP_URL}
      - SCHNAPSEN_AI_MODEL_URL=${SCHNAPSEN_AI_MODEL_URL}
      - SCHNAPSEN_AI_TOKEN=${SCHNAPSEN_AI_TOKEN}
      - DEBUG=${DEBUG}

networks:
  game-night-network:
    external: true
    driver: bridge